#!/bin/bash

# Setup script for shrtwrd multi-service platform
# This script helps you configure your environment safely

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_status() {
    echo -e "${YELLOW}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_header() {
    echo -e "${BLUE}=====================================${NC}"
    echo -e "${BLUE}  shrtwrd Platform Setup${NC}"
    echo -e "${BLUE}=====================================${NC}"
    echo
}

# Check if .env already exists
check_existing_config() {
    if [[ -f .env ]]; then
        echo -e "${YELLOW}Warning: .env file already exists.${NC}"
        read -p "Do you want to overwrite it? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            print_status "Keeping existing .env file"
            return 1
        fi
    fi
    return 0
}

# Collect user configuration
collect_config() {
    print_status "Please provide your configuration details:"
    echo

    # Droplet IP
    read -p "Enter your DigitalOcean Droplet IP: " DROPLET_IP
    while [[ ! $DROPLET_IP =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; do
        echo -e "${RED}Please enter a valid IP address${NC}"
        read -p "Enter your DigitalOcean Droplet IP: " DROPLET_IP
    done

    # Domain
    read -p "Enter your domain name (e.g., shrtwrd.com): " DOMAIN
    while [[ -z "$DOMAIN" ]]; do
        echo -e "${RED}Domain cannot be empty${NC}"
        read -p "Enter your domain name (e.g., shrtwrd.com): " DOMAIN
    done

    # Email
    read -p "Enter your email for Let's Encrypt: " EMAIL
    while [[ ! $EMAIL =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ ]]; do
        echo -e "${RED}Please enter a valid email address${NC}"
        read -p "Enter your email for Let's Encrypt: " EMAIL
    done

    # Project name (optional)
    read -p "Enter project name [shrtwrd-platform]: " PROJECT_NAME
    PROJECT_NAME=${PROJECT_NAME:-shrtwrd-platform}
}

# Create .env file
create_env_file() {
    print_status "Creating .env file..."

    cat > .env << EOF
# Environment Configuration
# Generated by setup script on $(date)

# DigitalOcean Droplet Configuration
DROPLET_IP=$DROPLET_IP
DOMAIN=$DOMAIN
EMAIL=$EMAIL

# Project Configuration
PROJECT_NAME=$PROJECT_NAME

# Optional: SSH Configuration
# SSH_KEY_PATH=~/.ssh/id_rsa
# SSH_USER=root

# Optional: Let's Encrypt Configuration
# ACME_CA=https://acme-v02.api.letsencrypt.org/directory
# ACME_CA_STAGING=https://acme-staging-v02.api.letsencrypt.org/directory

# Optional: Docker Configuration
# DOCKER_REGISTRY=your-registry.com
# DOCKER_TAG=latest

# Optional: Monitoring & Logging
# LOG_LEVEL=info
# ENABLE_METRICS=true
EOF

    print_success ".env file created successfully"
}

# Create Caddyfile from template
create_caddyfile() {
    if [[ -f Caddyfile.template ]]; then
        print_status "Creating Caddyfile from template..."
        cp Caddyfile.template Caddyfile
        print_success "Caddyfile created from template"
    else
        print_status "No Caddyfile template found, skipping..."
    fi
}

# Create manage script from template
create_manage_script() {
    if [[ -f manage.template.sh ]]; then
        print_status "Creating manage script from template..."
        cp manage.template.sh manage.sh
        chmod +x manage.sh
        print_success "Management script is ready"
    else
        print_status "No manage.template.sh found, skipping..."
    fi
}

# Make deploy script executable
setup_deploy_script() {
    if [[ -f deploy-multi.template.sh ]]; then
        print_status "Setting up deployment script..."
        cp deploy-multi.template.sh deploy-multi.sh
        chmod +x deploy-multi.sh
        print_success "Deployment script is ready"
    else
        print_error "deploy-multi.template.sh not found"
    fi
}

# Verify SSH access
test_ssh_access() {
    print_status "Testing SSH access to droplet..."

    if ssh -o ConnectTimeout=5 -o BatchMode=yes root@$DROPLET_IP exit 2>/dev/null; then
        print_success "SSH access confirmed"
        return 0
    else
        print_error "Cannot connect to $DROPLET_IP via SSH"
        echo -e "${YELLOW}Please ensure:${NC}"
        echo "  1. Your droplet is running"
        echo "  2. SSH key is added to the droplet"
        echo "  3. Port 22 is open in firewall"
        echo
        echo -e "${YELLOW}To add your SSH key to the droplet:${NC}"
        echo "  ssh-copy-id root@$DROPLET_IP"
        return 1
    fi
}

# Display next steps
show_next_steps() {
    echo
    print_success "Setup completed successfully!"
    echo
    echo -e "${BLUE}Next Steps:${NC}"
    echo "1. Configure your DNS A records:"
    echo "   • $DOMAIN -> $DROPLET_IP"
    echo "   • *.${DOMAIN} -> $DROPLET_IP"
    echo "   (or individually: one.$DOMAIN, two.$DOMAIN, etc.)"
    echo
    echo "2. Deploy your application:"
    echo "   ./deploy-multi.sh"
    echo
    echo "3. Test your deployment:"
    echo "   curl http://$DROPLET_IP"
    echo "   curl https://$DOMAIN (after DNS propagation)"
    echo
    echo "4. Manage your services:"
    echo "   ./manage.sh status    # Check service status"
    echo "   ./manage.sh logs      # View logs"
    echo "   ./manage.sh restart   # Restart services"
    echo
    echo -e "${YELLOW}Important Security Notes:${NC}"
    echo "• Your .env file contains sensitive information"
    echo "• Never commit .env to version control"
    echo "• The .gitignore is configured to exclude it"
    echo "• Template files (*.template.*) are safe to commit"
    echo
}

# Main function
main() {
    print_header

    # Check if config already exists
    if ! check_existing_config; then
        exit 0
    fi

    # Collect configuration
    collect_config

    # Create files
    create_env_file
    create_caddyfile
    create_manage_script
    setup_deploy_script

    # Test SSH (optional)
    echo
    read -p "Test SSH connection to droplet? (Y/n): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]] || [[ -z $REPLY ]]; then
        test_ssh_access
    fi

    # Show next steps
    show_next_steps
}

# Run main function
main "$@"
